# Generated by Django 5.1.7 on 2025-04-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visionfree_exam', '0002_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='created_at',
        ),
    ]
