# Generated by Django 5.1.7 on 2025-04-03 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visionfree_exam', '0003_rename_question_answer_question_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
    ]
