# Generated by Django 5.2 on 2025-04-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionfree_exam', '0005_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='option_a',
            field=models.CharField(default='Option A', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b',
            field=models.CharField(default='Option B', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c',
            field=models.CharField(default='Option C', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(default='Option D', max_length=255),
        ),
    ]
